server:
  port: 80


spring:
  application:
    name: FsMusic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE}?characterEncoding=UTF8&userSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}